version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: NGINX_PROXY
    volumes:
      - $cdir/nginx.conf:/etc/nginx/nginx.conf
      - $cdir/kps:/etc/nginx/kps
    ports:
      - 3129:3128
